# Minimal Supabase config to prevent CLI conflicts
project_id = "btnehreatcbzlglrrpqv"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.make-server-0b7c7173]

[functions.server]

[auth]
enabled = true