/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "btnehreatcbzlglrrpqv"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0bmVocmVhdGNiemxnbHJycHF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0Njg3MjcsImV4cCI6MjA3MDA0NDcyN30.y2fxLpPXb5FWBNgh9n_5YzXZRpY6I63Mf47WI-q-GIc"